version: "3"

services:
  frontend-admin:
    build: 
      context: ./frontend-admin
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - backend
      - db
    ports:
      - "3001:8080"
    volumes:
      - ./frontend-admin:/frontend-admin
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - backend
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - db
    ports:
      - "4001:3000"
    volumes:
      - ./backend:/backend
      - gem_cache:/usr/local/bundle/gems
    env_file: ./backend/.env
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle/gems
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  gem_cache:
  db_data:
