export const LIST_HOUSE_CATEGORY = 'LIST_HOUSE_CATEGORY';
export const GET_LIST_HOUSE_CATEGORY_SUCCESS = 'GET_LIST_HOUSE_CATEGORY_SUCCESS';
export const GET_LIST_HOUSE_CATEGORY_FAIL = 'GET_LIST_HOUSE_CATEGORY_FAIL';
export const ADD_HOUSE_CATEGORY = 'ADD_HOUSE_CATEGORY';
export const DELETE_HOUSE_CATEGORY = 'DELETE_HOUSE_CATEGORY';
